FROM node:11.10.0-alpine
env PORT 8080
#used by the bot
EXPOSE ${PORT}
EXPOSE 9229
WORKDIR /slackbot

COPY .env               .env
COPY .babelrc           .babelrc
COPY yarn.lock          yarn.lock
COPY .prettierrc        .prettierrc
COPY package.json       package.json
COPY .eslintrc.json     .eslintrc.json

RUN yarn

CMD ["yarn", "watch"]
